#!/usr/bin/env bash
# Transfer a file
if [[ $# < 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file=$1
	ip=$2
	user=$3
	key=$4
	
	if [[ $# == 3 ]]
	then
		scp -o StrictHostKeyChecking=no $file "$user@$ip:~/"
	else
		scp -i $key -o StrictHostKeyChecking=no $file "$user@$ip:~/"
	fi
fi
